[GH-45] add trollface
mattermost/mattermost-plugin-memes pull request #46
Opened 2021-02-18 13:44 UTC by aconitumnapellus

#### Summary
This PR adds the "Trollface" meme.

#### Ticket Link
#45

2021-02-19 10:50 UTC, hanzei requested changes
Thanks for adding more memes :tada: 

Could you please scale down `server/memelibrary/assets/images/trollface.jpg`? It huge right now.

Could you also please remove the unrelated changes in `server/memelibrary/assets.go`?

2021-02-19 10:50 UTC, hanzei commented on server/memelibrary/assets/metadata/trollface.yaml
> +  - Didnt learn anything
These examples are not orrect. Right now the text is split after the first white space so it should be `"Went to school" "Didnt learn anything"`.

![Screenshot from 2021-02-19 11-46-47](https://user-images.githubusercontent.com/16541325/108494756-338ec980-72a8-11eb-9fed-c87e701f7101.png)

2021-02-19 11:43 UTC, aconitumnapellus commented on server/memelibrary/assets/metadata/trollface.yaml
> +  - Didnt learn anything
Is it possible to test this out without a pattern?
As "make memelibrary && go run server/plugin.go -out aliens.jpg 'memes. memes everywhere" only works with a defined pattern...

2021-02-19 11:58 UTC, hanzei commented on server/memelibrary/assets/metadata/trollface.yaml
> +  - Didnt learn anything
You can deploy the plugin to your local server

2021-02-19 12:16 UTC, aconitumnapellus commented on server/memelibrary/assets/metadata/trollface.yaml
> +  - Didnt learn anything
![image](https://user-images.githubusercontent.com/44085060/108503412-3f7c8a80-72ac-11eb-9470-4de0e9471540.png)
Ive added a pattern for testing and have this now.

2021-03-01 10:33 UTC, hanzei approved these changes
LGTM :+1:

2021-03-01 10:33 UTC, hanzei commented
Tested locally

2021-03-01 10:34 UTC, merged