Update plugin.go
mattermost/mattermost-plugin-memes pull request #66
Opened 2023-02-22 21:03 UTC by theme1256

#### Summary
Possible fix for issue #41.
Changing from markdown image to image-attatchment.
I've never written Go before and havn't tried the edit (because I don't have the tools), but VSCode can't find any syntax errors.

#### Ticket Link
[Issue 41](https://github.com/mattermost/mattermost-plugin-memes/issues/41)

2023-02-22 21:06 UTC, hanzei requested changes
Could you please chare a before and after screenshot?

2023-02-22 21:57 UTC, theme1256 commented
Here's a screenshot showing one message before change (the blank one) and another efter change (the working one)
![Screenshot_20230222-225339](https://user-images.githubusercontent.com/9347753/220768475-870954a9-e785-4153-b1fd-a61fd1187cc3.png)

2023-02-23 09:10 UTC, hanzei requested changes
I'm hesitant to merge the PR as I don't full understand why the workaround is needed. Other plugin like https://github.com/moussetc/mattermost-plugin-giphy do use image and work on mobile.

2023-02-23 09:20 UTC, theme1256 commented
Sure, giphy works fine, but this plugin doesn't, despite both of them sending an image in markdown.

I did a bit of testing, manually sending images and gifs, and it turns out that gifs work just fine, but images don't.

So this PR is needed, because regular images don't work in the app when sendt in markdown, but fine when sendt as attatchments.

2023-02-23 21:36 UTC, theme1256 commented
Never mind.  
It actually doesn't work.

I tried building and uploading the plugin to my own server. This code works, but the image still doesn't show. I guess this will have to be fixed in the actual app and not in this plugin.

2023-02-23 21:36 UTC, closed without merging